### ISSUE TITLE
docs/index.md has a broken link

### ISSUE THREAD

**Issue by OrdiNeu** [guertinlab/seqOutBias#1]
In  seqOutBias/docs/index.md, the line: 
`- Genome tools ( [http://www.genometools.org](http://www.genometools.org) )`
appears to be broken. The correct URL appears to be http://genometools.org (without the www).

Just a heads up.

**Comment by OrdiNeu** [comment]
Ah, it looks like the latest commit fixed this issue. The only other related thing I've noticed is that the same issue occurs in docs/seqOutBias_user_guide.pdf, on page 1.

**Comment by guertinlab** [comment]
the genometools link in docs/seqOutBias_user_guide.pdf is now fixed
