### ISSUE TITLE
Error when compiling seqOutBias

### ISSUE THREAD

**Issue by arodel21** [guertinlab/seqOutBias#14]
Greetings,

I am installing seqOutBias in order to use it for seqOutATACBias package. 

I am following the instructions in the [user guide](https://guertinlab.github.io/seqOutBias/seqOutBias_user_guide.pdf). But the command `cargo build --release` is throwing the following error.

```
error: could not find native static library `hts`, perhaps an -L flag is missing?
error: aborting due to previous error
error: Could not compile `rust-htslib`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
I installed Rust following the instructions in their [website](https://www.rust-lang.org/tools/install) instead of using Brew.

I already tried downgrading Rust from 1.76.00 to 1.38.00 version and it didn't work. 
Do you have any advice on how to install this?

Thanks in advance.

**Comment by guertinlab** [comment]
I cannot reproduce the problem. Have you tried to the binaries from the latest release? https://github.com/guertinlab/seqOutBias/releases/tag/v1.4.0

**Comment by arodel21** [comment]
Thanks for the quick reply @guertinlab. 

Yes, I tried with that source code (.tar.gz file)

**Comment by guertinlab** [comment]
can you try a binary, select the binary that fits your computer architecture: https://github.com/guertinlab/seqOutBias/releases/download/v1.4.0/seqOutBias_v1.4.0.bin*

**Comment by kuangyuyen** [comment]
I have encountered a similar problem. The error message I got is as follows: rustc --explain E0310. It seems like a compatibility issue. I also used the source code (.tar.gz file), but not the binary file. With this, I was wondering which version of rust is suitable for seqOutBias?

Thanks.

**Comment by guertinlab** [comment]
I recommend trying the binaries if you are having trouble compiling
