### ISSUE TITLE
Error when running wigToBigWig

### ISSUE THREAD

**Issue by arodel21** [guertinlab/seqOutBias#15]
Greetings,

Once again I come for help.

I am running seqOutBias as part of another pipeline (seqOutATACBias) with the following command

`seqOutBias GRCz11.fa ATACseq.bam --read-size=50 --no-scale --strand-specific --custom-shift=4,-4 --bed=test_out.bed --bw=test_out_unscaled.bigWig`

But when seqOutBias gets to the part when it must run wigToBigWig It get an error.

```
wigToBigWig -keepAllChromosomes test_out_unscaled.bigWig "wigglefNrcR.tmp" "chromInfolCNoj.tmp"
invalid unsigned integer: "chrom=1"
```
But this part is weird, because it seems like at some point the argument files for wigToBigWig get unsorted because it should be running 
`wigToBigWig -keepAllChromosomes  "wigglefNrcR.tmp" "chromInfolCNoj.tmp" test_out_unscaled.bigWig` instead, with the bigwig file as output at the end of the command... 

I am almost sure that something is happening somewhere before that line, but I don't really know what it is.
I would very much appreciate your help.

Thanks in advance.
Best wishes.

**Comment by guertinlab** [comment]
There is a problem with the input files. Can you send me `wigglefNrcR.tmp` and `chromInfolCNoj.tmp` ? you should be able to find my email, Michael Guertin

**Comment by arodel21** [comment]
I have just sent the files to your email!

Thank you!
