### ISSUE TITLE
Counts

### ISSUE THREAD

**Issue by jamesdalg** [guertinlab/seqOutBias#16]
The original paper mentions a "counts" function that gets the counts of individual k-mers. That doesn't exist any longer, at least at the command line.
Is there some command to get a summary by individual k-mers?

**Comment by jamesdalg** [comment]
https://academic.oup.com/nar/article/46/2/e9/4602870?login=true



"- counts—code to tabulate k-mer counts"

**Comment by guertinlab** [comment]
The seqOutBias table step tallies the k-mer counts across the selected regions or the full genome. here is some random code that I used in the past for 7mers:
```shell
seqOutBias big_random.fa big_random.bam --strand-specific --stranded --shift-counts --kmer-mask=CNNNNNNN --read-size=7 --skip-bw --bed=est_big_7mer_map.bed
seqOutBias table big_random_7.7.0.0.tbl big_random.bam > test_big_7mer_map.txt

```

**Comment by jamesdalg** [comment]
That works! Thanks!

**Comment by jamesdalg** [comment]
In terms of interpretation, the output is the index, the sequence, the plus expected read counts, the minus expected read counts, the plus observed read counts, and the minus observed read counts, correct(
https://github.com/guertinlab/seqOutBias/blob/1446ebc35d1cf5ede03fe87fab7650a5e8c0516d/src/counts.rs#L398)? From here, scaling happens by expected/observed=scaling_factor, correct?

**Comment by guertinlab** [comment]
I don't know the columns off the top of my head, but this seems right. The exp/obs IS correct.

**Comment by jamesdalg** [comment]
Thanks for clarifying. Your package is really solid and well thought out, I think.
