### ISSUE TITLE
read-size parameter doesn't work in tallymer command

### ISSUE THREAD

**Issue by hwlim** [guertinlab/seqOutBias#3]
Hi, I tried a read-size parameter in tallymer command
> seqOutBias tallymer genome.fa 50

However, its default value 36 seem to override the given value always,
thus create files for 36 read size only.
genome.tal_36.gtTxt.gz
genome.tal_36.mbd
genome.tal_36.mct
genome.tal_36.mer

I can create files for 50bp only when I run seqtable with --read-size option.

Thanks.

**Comment by andrelmartins** [comment]
Hi,

You are indeed correct, the tallymer command had a bug when executed separately, causing it to take the default value instead of the supplied one. I have just published a fix (see release v1.1.1).

Thank you!

**Comment by hwlim** [comment]
Thanks a lot  for the quick fix.
