### ISSUE TITLE
error when compile the seqOutBias

### ISSUE THREAD

**Issue by lynnyummy** [guertinlab/seqOutBias#4]
Hi, I am trying to use SeqOutBia to shift the reads bias in my ATAC-seq data. I downloaded the Rust+cargo from Anaconda, and git clone the seqOutBias. But I meet the issue ( error: could not compile `url`.) when try to compile the seqOutBias, following is the record. 
Could you please help to solve this issue? Thank you so much!

error[E0713]: borrow may still be in use when destructor runs
   --> /data/home/myaccount/.cargo/registry/src/github.com-1ecc6299db9ec823/url-1.5.1/src/form_urlencoded.rs:251:40
    |
249 | impl<'a> Target for ::UrlQuery<'a> {
    |      -- lifetime `'a` defined here
250 |     fn as_mut_string(&mut self) -> &mut String { &mut self.url.serialization }
251 |     fn finish(self) -> &'a mut ::Url { self.url }
    |                                        ^^^^^^^^ - here, drop of `self` needs exclusive access to `*self.url`, because the type `UrlQuery<'_>` implements the `Drop` trait
    |                                        |
    |                                        returning this value requires that `*self.url` is borrowed for `'a`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0713`.
error: could not compile `url`.

Caused by:
  process didn't exit successfully: `rustc --crate-name url /data/home/myaccount/.cargo/registry/src/github.com-1ecc6299db9ec823/url-1.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=1cbca242ad47a64c -C extra-filename=-1cbca242ad47a64c --out-dir /data/my_ATAC/seqOutBias/target/debug/deps -L dependency=/data/my_ATAC/seqOutBias/target/debug/deps --extern idna=/data/my_ATAC/seqOutBias/target/debug/deps/libidna-9e33c91c635846a5.rmeta --extern matches=/data/my_ATAC/seqOutBias/target/debug/deps/libmatches-b51182e1331daf6a.rmeta --extern percent_encoding=/data/my_ATAC/seqOutBias/target/debug/deps/libpercent_encoding-f1fe04f305bf564d.rmeta --cap-lints allow` (exit code: 1)adjustment/seqOutBias/target/debug/deps/libpercent_encoding-f1fe04f305bf564d.rmeta --cap-lints allow` (exit code: 1)

**Comment by guertinlab** [comment]
Is this when you execute: `cargo build --release` 

what version of Rust are you running?

by the way, recently I have been optimizing the use of seqOutBias with ATAC-seq and I suggest trimming the first four bases off each read prior to alignment. The k-mer mask still needs to be optimized as well. email me if you want technical help on the implementation for ATAC
-Mike

**Comment by guertinlab** [comment]
I would also recommend trying the release as opposed to cloning the repository: 
https://github.com/guertinlab/seqOutBias/releases/tag/v1.2.0
https://github.com/guertinlab/seqOutBias/archive/v1.2.0.tar.gz

**Comment by lynnyummy** [comment]
> Is this when you execute: `cargo build --release`
> 
> what version of Rust are you running?
> 
> by the way, recently I have been optimizing the use of seqOutBias with ATAC-seq and I suggest trimming the first four bases off each read prior to alignment. The k-mer mask still needs to be optimized as well. email me if you want technical help on the implementation for ATAC
> -Mike

Hi Mike,

Thanks for your reply! Yes I meet the issue when I used cargo build --release. I use rustup 1.21.1 (7832b2ebe 2019-12-20). 
I downloaded the new release https://github.com/guertinlab/seqOutBias/archive/v1.2.0.tar.gz
and installed again, it works! Thank you so much! 

Regarding you mentioned trimming the first four reads before alignment, I think I could try this step! Thanks for your clarification!

**Comment by lynnyummy** [comment]
Hi Mike,
I meet few issues,
1. I ran "seqOutBias", and got the error, "################### Creating mappability file using tallymer ###################
failed to execute 'gt suffixerator': No such file or directory (os error 2)". 
2. According to the link you send, I changed the command to "seqOutBias tallymer" , and got this error 
"Could not decode 'my_mapped_ATAC.bam' to u16 for '<read-size>"

Is it because of I need to trim the first four reads of each reads?

Thank you!

**Comment by lynnyummy** [comment]
> I would also recommend trying the release as opposed to cloning the repository:
> https://github.com/guertinlab/seqOutBias/releases/tag/v1.2.0
> https://github.com/guertinlab/seqOutBias/archive/v1.2.0.tar.gz

Hi Mike,
I meet few issues,

I ran "seqOutBias", and got the error, "################### Creating mappability file using tallymer ###################
failed to execute 'gt suffixerator': No such file or directory (os error 2)".
According to the link you send, I changed the command to "seqOutBias tallymer" , and got this error
"Could not decode 'my_mapped_ATAC.bam' to u16 for '"
Is it because of I need to trim the first four reads of each reads?

Thank you!

**Comment by guertinlab** [comment]
Do you have the dependency genometools (gt) installed?

**Comment by lynnyummy** [comment]
> Do you have the dependency genometools (gt) installed?

Yes I installed both genometools and WigtoBigWig in the same enviroment.

**Comment by lynnyummy** [comment]
> Do you have the dependency genometools (gt) installed?

Hi Mike, I finally solved the issues! yes need to copy the gt to the path...
I got the results, next I will analysis them, thanks for your helps!
