### ISSUE TITLE
Help with installing/compiling

### ISSUE THREAD

**Issue by josruirod** [guertinlab/seqOutBias#5]
Hi and thanks for the work in the software

So I'm trying to install this and getting some errors, could you help?
So I have:

`wget https://github.com/guertinlab/seqOutBias/archive/v1.2.0.tar.gz`
`tar xvzf v1.2.0.tar.gz`
`cd seqOutBias-1.2.0/`
`cargo build --release`

And it starts downloading and compiling but it ends with this error:

> Compiling miniz-sys v0.1.9
   Compiling url v1.5.1
   Compiling regex v0.1.80
error[E0713]: borrow may still be in use when destructor runs
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/url-1.5.1/src/form_urlencoded.rs:251:40
    |
249 | impl<'a> Target for ::UrlQuery<'a> {
    |      -- lifetime `'a` defined here
250 |     fn as_mut_string(&mut self) -> &mut String { &mut self.url.serialization }
251 |     fn finish(self) -> &'a mut ::Url { self.url }
    |                                        ^^^^^^^^ - here, drop of `self` needs exclusive access to `*self.url`, because the type `UrlQuery<'_>` implements the `Drop` trait
    |                                        |
    |                                        returning this value requires that `*self.url` is borrowed for `'a`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0713`.
error: Could not compile `url`.
Build failed, waiting for other jobs to finish...
error: build failed

Does anyone have any idea? cargo version is cargo 0.19.0 and rustc 1.46.0 (04488afe3 2020-08-24)

Thank you very much for the support

**Comment by josruirod** [comment]
I have also tried installing rust 1.18 because this was the minimal version according to the user guide, and I'm now getting this error:

> error: linking with `/miniconda3/envs/seqoutbias/bin/x86_64-conda-linux-gnu-cc` failed: exit code: 1


And later on: 

> note: miniconda3/envs/seqoutbias/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lz
         collect2: error: ld returned 1 exit status
error: aborting due to previous error
error: Could not compile `seqOutBias`.

Maybe something to do with miniconda?

**Comment by mjg54** [comment]
We recently included an update to the master file, but did not issue a new release. The transition from rust to 1.39+ caused an issue that was resolved by changing url 1.5.1 to url 1.7.2 in commit e85a0373e7b9cc2375df07bd3f577f69f20b3510 --this is causing the 
`error: Could not compile url.`
Try to download the master, or change to rust 1.38 and use the release. Either should fix the installation issue.

**Comment by josruirod** [comment]
Thanks for the help, I have dowloaded the master and now it seems to be working better, but I'm getting another error. After many warnings, this is the final of the log. Some issue with zlib? Maybe it's relevant that I'm in a conda environment?
I have already exported an LD_LIBRARY_PATH containing the path to libz.a and libz.so 

Thanks for the support

> warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()
>    --> src/scale.rs:236:82
>     |
> 236 |                 println!("Error: Failed to open BAM file '{}': {}", bamfile, err.description());
>     |                                                                                  ^^^^^^^^^^^
> 
> error: linking with `/some/path/miniconda3/envs/seqoutbias/bin/x86_64-conda-linux-gnu-cc` failed: exit code: 1
>   |
>   = note: "/some/path/miniconda3/envs/seqoutbias/bin/x86_64-conda-linux-gnu-cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.0.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.1.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.10.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.11.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.12.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.13.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.14.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.15.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.2.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.3.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.4.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.5.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.6.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.7.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.8.rcgu.o" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.seqoutbiaslib.5zct80nh-cgu.9.rcgu.o" "-o" "/some/path/bin/seqOutBias/target/release/deps/libseqoutbiaslib.so" "-Wl,--version-script=/scratch-local/jlruiz/2388338/rustcl6oLy0/list" "/some/path/bin/seqOutBias/target/release/deps/seqoutbiaslib.4wcx320s53tq811l.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/some/path/bin/seqOutBias/target/release/deps" "-L" "/some/path/bin/seqOutBias/target/release/build/miniz-sys-b0061f7aa8c6e57d/out" "-L" "/some/path/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-htslib-0.12.1/htslib" "-L" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/some/path/bin/seqOutBias/target/release/deps/libtempfile-a0d7e6111110d114.rlib" "/some/path/bin/seqOutBias/target/release/deps/librand-ccc1facc3ff5de2c.rlib" "/some/path/bin/seqOutBias/target/release/deps/librand-a6238146f240b5d1.rlib" "/some/path/bin/seqOutBias/target/release/deps/librust_htslib-4bc4513c14a02300.rlib" "/some/path/bin/seqOutBias/target/release/deps/libbitflags-48f464bd19b7f22d.rlib" "/some/path/bin/seqOutBias/target/release/deps/liblazy_static-56fa2113cc95286d.rlib" "/some/path/bin/seqOutBias/target/release/deps/libieee754-a269b0b51448db44.rlib" "/some/path/bin/seqOutBias/target/release/deps/liburl-04927a3e634b1b95.rlib" "/some/path/bin/seqOutBias/target/release/deps/libpercent_encoding-94837846d59b0c17.rlib" "/some/path/bin/seqOutBias/target/release/deps/libidna-44324678bd64c40f.rlib" "/some/path/bin/seqOutBias/target/release/deps/libunicode_normalization-a1e8313642a7452c.rlib" "/some/path/bin/seqOutBias/target/release/deps/libunicode_bidi-295e44355ec8efaf.rlib" "/some/path/bin/seqOutBias/target/release/deps/libmatches-2da560489ad6d579.rlib" "/some/path/bin/seqOutBias/target/release/deps/libcustom_derive-3a079b1f770227ab.rlib" "/some/path/bin/seqOutBias/target/release/deps/libnewtype_derive-7a57982e7d659dd3.rlib" "/some/path/bin/seqOutBias/target/release/deps/libquick_error-23c155a560de6a42.rlib" "/some/path/bin/seqOutBias/target/release/deps/libitertools-b1a823942e3769ee.rlib" "/some/path/bin/seqOutBias/target/release/deps/libeither-7389377cdf8cb94c.rlib" "/some/path/bin/seqOutBias/target/release/deps/libflate2-75f05cc5b006c320.rlib" "/some/path/bin/seqOutBias/target/release/deps/libminiz_sys-9ab098501e1dd69b.rlib" "/some/path/bin/seqOutBias/target/release/deps/liblibc-35a1dd46b45d4e04.rlib" "/some/path/bin/seqOutBias/target/release/deps/libbincode-30028abe95642bc4.rlib" "/some/path/bin/seqOutBias/target/release/deps/libserde-df90b161f4f2673e.rlib" "/some/path/bin/seqOutBias/target/release/deps/libnum_traits-48fb6e43103e91cf.rlib" "/some/path/bin/seqOutBias/target/release/deps/libbyteorder-e850ce2a1345567f.rlib" "/some/path/bin/seqOutBias/target/release/deps/librustc_serialize-5cf7344736bc24dd.rlib" "-Wl,--start-group" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-cf0f33af3a901778.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-daf8c2d692e6eca4.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-24e8f97647425e48.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-85ed7d2b484c05a9.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-89de2c581262ec09.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-3b0db98e62ed7d75.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-c60847f9a163de82.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-0bb9b63424f4fc5d.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-3f74d829e37fa40e.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-0e9d83ff06f1a7ad.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-2c8c904efaf7c40b.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-cbfb51de52131460.rlib" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-97497c26fddb7882.rlib" "-Wl,--end-group" "/some/path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f1a9d8c443e20b5e.rlib" "-Wl,-Bdynamic" "-lz" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
>   = note: /some/path/miniconda3/envs/seqoutbias/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lz
>           collect2: error: ld returned 1 exit status
>           
> 
> error: aborting due to previous error; 60 warnings emitted
> 
> error: could not compile `seqOutBias`.

**Comment by mjg54** [comment]
since this is a compilation error, have you tried to execute the precompiled binaries? Again, these may require rust 1.38. 

I believe you want the following precompiled bins:
https://github.com/guertinlab/seqOutBias/releases/download/v1.2.0/seqOutBias_v1.2.0.bin.linux.x86_64.tgz

**Comment by josruirod** [comment]
OK thanks for the help. I can confirm that these binaries are working. Also, I could solve the problem of the compiler not detecting lz by adding soft link to the libz.a and libz.so in the directory that rust was looking for the libs (in my case /path/miniconda3/envs/seqoutbias/lib/rustlib/x86_64-unknown-linux-gnu/lib)

Thanks for the support, everyhing seems to be working now

**Comment by mjg54** [comment]
if you are using this for ATAC-seq (I assume, because I am also receiving your PEPATAC issues), then you should be aware that @JWolpe is working on characterizing and correcting the Tn5 bias in a way that improves substantially upon the original parameters. Depending upon how you pre-process the ATAC reads, we have specific recommendations for the plus and minus offsets and the k-mer specifications. You are welcome to email me if you want further information.

**Comment by josruirod** [comment]
OK, thank you very much for the sugestion and the support. Will do. Regards

**Comment by HouyuZhang** [comment]
Hi, developers,
Thanks for this nice package for correcting enzyme bias. 
I currently have a bam file mapped using bowtie2 and discarded PCR duplicates using Picard. In the downstream analysis, I want to use **seqOutBias** for ATAC-seq reads correction. As for the parameter, I found a guideline from the vignette (timed June 7, 2017, by Michael Guertin): `plus_mask=NXNXXXCXXNNXNNNXXN`
`seqOutBias ~/DNase_ENCODE/hg38.fa ${name}_minus.bam --kmer-mask ${minus_mask} --bw=${name}_minus_${minus_mask}-mer.bigWig --shift-counts --read-size=75`
Since the ATAC-seq reads were generally shifted to account for the 9-bp target duplication, which is not usual as other sequencing data, like DNase-seq. I wonder is there any possibility that you can share some more detailed suggestions on correcting ATAC-seq data? For example, how to handle the 9-bp Tn5 target duplication and how to set the `--kmer-mask` parameter? 
Besides, I'm curious that except for the ATAC-seq analysis, will ATAC-seq bias correction have benefits in other analyses, like peak calling and nucleosome calling?
Thank you very much for any comments!

**Comment by guertinlab** [comment]
It turns out that Tn5 bias is complicated and not easily, measured with k-mer counts. We recently implemented a `--custom-shift` option is version 1.3.0 and you can specify plus and minus shifts with this option. Although we argue that a shift of 4,-3 is optimal and most similar to the `--shift-counts` option in seqOutBias for enzymes like DNase. The reason Tn5 bias is difficult to correct is because the enzyme is dimeric and sequences far away can affect cleavage. A students in the lab is working to fully describe and correct the bias, but we are confident a k-mer correction is not sufficient. The benefits of bias correction diminish if you are analyzing ATAC data a single nucleotide resolution.

**Comment by HouyuZhang** [comment]
Thanks for the reply!
I get a sense of why the correction of the Tn5 enzyme is hard. I'm curious whether the dinucleotide-based methods will assist in correcting the Tn5 bias since the Tn5 is a dimer. As a [benchmark study](https://www.nature.com/articles/nbt.2486) reported that these modeling methods might differ according to the DBP studied. However, if any information or result is private, please ignore this question. I look forward to more accurate algorithms in the future.  
Thanks for all!
